# Generated by Django 5.2.15 on 2026-06-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multitenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('linkedin_url', models.CharField(max_length=400)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('headline', models.CharField(blank=True, max_length=400)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('current_title', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('started_current_role_at', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'db_table': 'sourcing_candidate',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('icp', models.JSONField(blank=True, default=dict)),
                ('strategy', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sourcing', 'Sourcing'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'db_table': 'sourcing_role',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutreachDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('linkedin', 'Linkedin'), ('email', 'Email')], max_length=12)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('reject_reason', models.CharField(blank=True, max_length=400)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='sourcing.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='sourcing.role')),
            ],
            options={
                'db_table': 'sourcing_outreach_draft',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('verdict', models.CharField(choices=[('fit', 'Fit'), ('drop', 'Drop')], max_length=8)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('drop_reason', models.CharField(blank=True, max_length=400)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='sourcing.candidate')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='sourcing.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'db_table': 'sourcing_score',
                'ordering': ('-score',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourcingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('budget_exhausted', 'Budget Exhausted')], default='pending', max_length=20)),
                ('temporal_workflow_id', models.CharField(blank=True, max_length=255)),
                ('scanned_companies', models.PositiveIntegerField(default=0)),
                ('found_candidates', models.PositiveIntegerField(default=0)),
                ('fit_candidates', models.PositiveIntegerField(default=0)),
                ('drafted', models.PositiveIntegerField(default=0)),
                ('budget_used', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='sourcing.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'db_table': 'sourcing_run',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_seen_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_candidates', to='sourcing.sourcingrun'),
        ),
        migrations.CreateModel(
            name='TargetCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('linkedin_url', models.CharField(blank=True, max_length=400)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('prev_employer', 'Prev Employer')], default='seed', max_length=16)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='sourcing.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'db_table': 'sourcing_target_company',
                'ordering': ('depth', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('recent_joiner', 'Recent Joiner'), ('prev_employer', 'Prev Employer'), ('network', 'Network')], max_length=16)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('from_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_edges', to='sourcing.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
                ('to_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_edges', to='sourcing.candidate')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='sourcing.role')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edges', to='sourcing.sourcingrun')),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitted_edges', to='sourcing.targetcompany')),
            ],
            options={
                'db_table': 'sourcing_lead_edge',
                'ordering': ('depth', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('experiences', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('fetched_at', models.DateTimeField()),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='sourcing.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'db_table': 'sourcing_enrichment',
                'abstract': False,
                'indexes': [models.Index(fields=['tenant'], name='sourcing_en_tenant__9028cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdemKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=255)),
                ('kind', models.CharField(blank=True, max_length=64)),
                ('ref', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'db_table': 'sourcing_idem_key',
                'abstract': False,
                'indexes': [models.Index(fields=['tenant'], name='sourcing_id_tenant__d14011_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uniq_idem_key_per_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant'], name='sourcing_ro_tenant__b518b9_idx'),
        ),
        migrations.AddIndex(
            model_name='outreachdraft',
            index=models.Index(fields=['tenant'], name='sourcing_ou_tenant__2c373e_idx'),
        ),
        migrations.AddConstraint(
            model_name='outreachdraft',
            constraint=models.UniqueConstraint(fields=('tenant', 'candidate', 'role', 'channel'), name='uniq_draft_per_candidate_role_channel'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['tenant'], name='sourcing_sc_tenant__753c79_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('tenant', 'candidate', 'role'), name='uniq_score_per_candidate_role'),
        ),
        migrations.AddIndex(
            model_name='sourcingrun',
            index=models.Index(fields=['tenant'], name='sourcing_ru_tenant__0ad94d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['tenant'], name='sourcing_ca_tenant__6263a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('tenant', 'linkedin_url'), name='uniq_candidate_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='targetcompany',
            index=models.Index(fields=['tenant'], name='sourcing_ta_tenant__ef3bf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='targetcompany',
            constraint=models.UniqueConstraint(fields=('tenant', 'role', 'name'), name='uniq_target_company_per_role'),
        ),
        migrations.AddIndex(
            model_name='leadedge',
            index=models.Index(fields=['tenant'], name='sourcing_le_tenant__290a6a_idx'),
        ),
    ]
