# Generated by Django 5.2.15 on 2026-06-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcompany',
            name='discovered_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surfaced_companies', to='sourcing.candidate'),
        ),
    ]
