# Generated by Django 5.2.15 on 2026-06-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_targetcompany_discovered_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrichment',
            options={'ordering': ('-fetched_at',)},
        ),
    ]
