# Generated by Django 5.2.15 on 2026-06-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0003_alter_enrichment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='score',
            name='summary',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
