# Generated by Django 5.2.15 on 2026-06-15 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenant', '0001_initial'),
        ('sourcing', '0004_score_criteria_score_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('session_cookie', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Expired'), ('disconnected', 'Disconnected')], default='disconnected', max_length=16)),
                ('daily_invite_limit', models.PositiveSmallIntegerField(default=20)),
                ('invites_sent_today', models.PositiveSmallIntegerField(default=0)),
                ('invites_reset_on', models.DateField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.CharField(blank=True, max_length=150)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'db_table': 'sourcing_linkedin_account',
                'abstract': False,
                'indexes': [models.Index(fields=['tenant'], name='sourcing_li_tenant__670bd7_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_linkedin_account_per_tenant')],
            },
        ),
    ]
